### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by sokmontrey** [AleDenshi/comfy.guide#10]
I'm thinking of redesigning the site. The current design is fine and simple but can be improve further. 

I'm willing to adjust the layout, color scheme, font, and a few other feature for a better readability and navigation. This should not affect the simplicity and comfyness aspect of the site.

I'll update with a quick Figma design later in this issue. And I just want to get an approval first before actually started coding it.

**Comment by sokmontrey** [comment]
I started to realized that I'm creating a problem that doesn't exist. Here is what I'm aiming for. 

![lightmode](https://github.com/AleDenshi/comfy.guide/assets/49610016/9ac71032-4f66-443b-8001-118aa3093d72)

![darkmode](https://github.com/AleDenshi/comfy.guide/assets/49610016/a16f88c5-0f3e-4ce4-98bd-99fdfd77715a)

![lightmode-1](https://github.com/AleDenshi/comfy.guide/assets/49610016/f3a23299-03ed-45fa-8428-2d2cbde1fcda)

Not much has changed. 
- All fonts will be web-safe
- Paragraphs' font should be any sans-serif equivalent
- Home page is a little more compact (desktop).
- Border is lighter
- A little less contrast between background and foreground.
- for each of the article pages, they will have the width of about 50vw for desktop view.

**Comment by AleDenshi** [comment]
I changed the design a little in the latest commit, what do y'all think of it so far?

**Comment by sokmontrey** [comment]
This is perfect. A little narrower width for the article page would be nice.

**Comment by AleDenshi** [comment]
I added some fixes in the latest commit. Glad it's looking better!
