### ISSUE TITLE
Bitcoin donation option

### ISSUE THREAD

**Issue by MaxLPM** [AleDenshi/comfy.guide#14]
While Monero is the best in terms of privacy, Bitcoin is more popular, so there should be an option to add a Bitcoin address for donations as well. I've noticed that people are more likely to donate Bitcoin rather than any other cryptocurrency, but if we want to push Monero it can be selected in bold or a "(preferred)" text can be added, and Bitcoin will be listed below

**Comment by AleDenshi** [comment]
I will add this as soon as I get done revamping the whole author system! Great idea.

**Comment by AleDenshi** [comment]
This was added when I revamped the links system. Any other crypto can be added now too, so long as an appropriate icon svg can be provided.
