### ISSUE TITLE
Weird layout behaviour on main page

### ISSUE THREAD

**Issue by MaxLPM** [AleDenshi/comfy.guide#15]
It used to be that on the main page "Server Software" was before "Client Software". But if it gets rendered with the -D flag, or "draft: true" is removed from the gentoo or kisslinux pages, the "Client Software" articles jump right above the "Server Software" ones. I have no idea why this is the case, maybe because it sorts by modification date? But adding .ByTitle or .ByTitle.Reverse to .Site.Sections solves it. We should decide what the correct layout of the articles should be, because an inconsistency like this would be pretty annoying

**Comment by AleDenshi** [comment]
The layout works by listing every section on the site based off which one has been updated most recently. I will change it to list server software before client software, since that seems to be what people like the most.

**Comment by AleDenshi** [comment]
Fixed in the latest PR.
