### ISSUE TITLE
Can't access with russian ip

### ISSUE THREAD

**Issue by WeAreLiving1984** [AleDenshi/comfy.guide#32]
Same goes for denshi.org

Is this intentional?

globalcheck.net:
![image](https://github.com/user-attachments/assets/0715a542-c884-4cb2-8461-9aa6a816a4f8)

P.S. Thank you for your guides, learned a lot from last arch linux video!

**Comment by AleDenshi** [comment]
This is not intentional. You should contact my VPS provider (BuyVM/Frantech) about this. The VPS server itself is located in Luxembourg.
