### ISSUE TITLE
Push issue

### ISSUE THREAD

**Issue by Yoproo20** [AleDenshi/comfy.guide#7]
Git newbie here: This could be an error on my side but I spent a while writing an article getting the SVG of the tool and then it says I don't have push access, is there another method I am supposed to use primarily?

**Comment by prathamdupare** [comment]
Yes, to push your changes, you should first fork the repository, make the necessary changes, and then push them to your fork. Afterward, you can create a pull request, and the maintainer will review and merge it.

For more info, check  [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), it might help.

**Comment by AleDenshi** [comment]
Hi there yoproo20. If things are getting complicated, I might make a more detailed video on how to push changes. Thanks for letting me know.
