### ISSUE TITLE
(docs) Deployment missing

### ISSUE THREAD

**Issue by Logianer** [AleDenshi/comfy.guide#8]
**What's missing?**
Guide/Way to easily deploy the created site on a static webserver.

**What could be done?**
Here are some examples:

1. Give some documentation about how to build the hugo site manually and where to find the generated HTML-content.
2. Use github actions to automatically deploy to a webserver on push. This would also require *some* documentation, as well as a new `develop`-branch to "cache" commits that should not be present on the live version.
3. Write a script and add it to the repo that interactively or through a config file, builds and uploads the site via ssh/ftp to a remote server.

**Comment by AleDenshi** [comment]
Hi there loglaner. To build a hugo site, simply run `hugo` in the site directory. I'm not sure exactly who's deploying the site in production (are there people wanting to run mirrors?) so I'm not sure I'd add that to the documentation.

**Comment by Logianer** [comment]
Oh so there is no way to like generate static html files from the hugo "code"? Now my question seems more like a hugo-related problem/request

**Comment by AleDenshi** [comment]
To generate HTML, simply run `hugo` in the Hugo server directory (comfy.guide) and all the HTML files will be generated in the `public/` directory. Sorry for not specifying earlier.

**Comment by AleDenshi** [comment]
I'll also clarify that the `public/` directory is listed under `.gitignore` for this repository, to make sure people don't accidentally add and commit rendered HTML. This also applies to the temporary lock file Hugo generates when previewing the site.
